var data = {systeme:[{"id":0,"name":"Carloss","x":8,"y":18,"z":0,"fraktion_id":1,"quadrant_id":1,"quadrant_x":0,"quadrant_y":0,"sektor_id":1},
{"id":1,"name":"El Dorado","x":26,"y":12,"z":0,"fraktion_id":1,"quadrant_id":1,"quadrant_x":0,"quadrant_y":0,"sektor_id":1},
{"id":2,"name":"Giunta","x":18,"y":8,"z":0,"fraktion_id":1,"quadrant_id":1,"quadrant_x":0,"quadrant_y":0,"sektor_id":1},
{"id":3,"name":"Grajeda","x":8,"y":8,"z":0,"fraktion_id":1,"quadrant_id":1,"quadrant_x":0,"quadrant_y":0,"sektor_id":1},
{"id":4,"name":"Hermann","x":18,"y":15,"z":0,"fraktion_id":1,"quadrant_id":1,"quadrant_x":0,"quadrant_y":0,"sektor_id":1},
{"id":5,"name":"Kier","x":14,"y":22,"z":0,"fraktion_id":1,"quadrant_id":1,"quadrant_x":0,"quadrant_y":0,"sektor_id":1},
{"id":6,"name":"Leon","x":21,"y":24,"z":0,"fraktion_id":1,"quadrant_id":1,"quadrant_x":0,"quadrant_y":0,"sektor_id":1},
{"id":7,"name":"McCall","x":26,"y":27,"z":0,"fraktion_id":1,"quadrant_id":1,"quadrant_x":0,"quadrant_y":0,"sektor_id":1},
{"id":8,"name":"Mira","x":4,"y":21,"z":0,"fraktion_id":1,"quadrant_id":1,"quadrant_x":0,"quadrant_y":0,"sektor_id":1},
{"id":9,"name":"Paylode","x":26,"y":20,"z":0,"fraktion_id":1,"quadrant_id":1,"quadrant_x":0,"quadrant_y":0,"sektor_id":1},
{"id":10,"name":"TCSC1569","x":8,"y":28,"z":0,"fraktion_id":0,"quadrant_id":1,"quadrant_x":0,"quadrant_y":0,"sektor_id":1},
{"id":11,"name":"TCSC3102","x":20,"y":2,"z":0,"fraktion_id":0,"quadrant_id":1,"quadrant_x":0,"quadrant_y":0,"sektor_id":1},
{"id":12,"name":"Avalon","x":4,"y":24,"z":0,"fraktion_id":1,"quadrant_id":2,"quadrant_x":1,"quadrant_y":0,"sektor_id":1},
{"id":13,"name":"Babel","x":19,"y":20,"z":0,"fraktion_id":1,"quadrant_id":2,"quadrant_x":1,"quadrant_y":0,"sektor_id":1},
{"id":14,"name":"Baroda","x":16,"y":16,"z":0,"fraktion_id":1,"quadrant_id":2,"quadrant_x":1,"quadrant_y":0,"sektor_id":1},
{"id":15,"name":"Britannia","x":13,"y":25,"z":0,"fraktion_id":1,"quadrant_id":2,"quadrant_x":1,"quadrant_y":0,"sektor_id":1},
{"id":16,"name":"Cibola","x":16,"y":4,"z":0,"fraktion_id":1,"quadrant_id":2,"quadrant_x":1,"quadrant_y":0,"sektor_id":1},
{"id":17,"name":"Dallas","x":26,"y":2,"z":0,"fraktion_id":1,"quadrant_id":2,"quadrant_x":1,"quadrant_y":0,"sektor_id":1},
{"id":18,"name":"Dis","x":11,"y":9,"z":0,"fraktion_id":1,"quadrant_id":2,"quadrant_x":1,"quadrant_y":0,"sektor_id":1},
{"id":19,"name":"Elena","x":18,"y":26,"z":0,"fraktion_id":1,"quadrant_id":2,"quadrant_x":1,"quadrant_y":0,"sektor_id":1},
{"id":20,"name":"Gomorrah","x":27,"y":7,"z":0,"fraktion_id":1,"quadrant_id":2,"quadrant_x":1,"quadrant_y":0,"sektor_id":1},
{"id":21,"name":"Haven","x":27,"y":15,"z":0,"fraktion_id":1,"quadrant_id":2,"quadrant_x":1,"quadrant_y":0,"sektor_id":1},
{"id":22,"name":"Jericho","x":23,"y":28,"z":0,"fraktion_id":1,"quadrant_id":2,"quadrant_x":1,"quadrant_y":0,"sektor_id":1},
{"id":23,"name":"New Atlantis","x":13,"y":20,"z":0,"fraktion_id":1,"quadrant_id":2,"quadrant_x":1,"quadrant_y":0,"sektor_id":1},
{"id":24,"name":"Panama","x":7,"y":18,"z":0,"fraktion_id":1,"quadrant_id":2,"quadrant_x":1,"quadrant_y":0,"sektor_id":1},
{"id":25,"name":"Sheol","x":11,"y":14,"z":0,"fraktion_id":1,"quadrant_id":2,"quadrant_x":1,"quadrant_y":0,"sektor_id":1},
{"id":26,"name":"Sodom","x":22,"y":10,"z":0,"fraktion_id":1,"quadrant_id":2,"quadrant_x":1,"quadrant_y":0,"sektor_id":1},
{"id":27,"name":"Tanis","x":18,"y":13,"z":0,"fraktion_id":1,"quadrant_id":2,"quadrant_x":1,"quadrant_y":0,"sektor_id":1},
{"id":28,"name":"Ubar","x":4,"y":13,"z":0,"fraktion_id":1,"quadrant_id":2,"quadrant_x":1,"quadrant_y":0,"sektor_id":1},
{"id":29,"name":"Xualla","x":4,"y":6,"z":0,"fraktion_id":1,"quadrant_id":2,"quadrant_x":1,"quadrant_y":0,"sektor_id":1},
{"id":30,"name":"17-AR","x":3,"y":10,"z":0,"fraktion_id":1,"quadrant_id":3,"quadrant_x":2,"quadrant_y":0,"sektor_id":2},
{"id":31,"name":"Beta","x":22,"y":2,"z":0,"fraktion_id":1,"quadrant_id":3,"quadrant_x":2,"quadrant_y":0,"sektor_id":2},
{"id":32,"name":"Capella","x":15,"y":12,"z":0,"fraktion_id":1,"quadrant_id":3,"quadrant_x":2,"quadrant_y":0,"sektor_id":2},
{"id":33,"name":"Castor","x":20,"y":27,"z":0,"fraktion_id":1,"quadrant_id":3,"quadrant_x":2,"quadrant_y":0,"sektor_id":2},
{"id":34,"name":"Crab-12","x":12,"y":9,"z":0,"fraktion_id":1,"quadrant_id":3,"quadrant_x":2,"quadrant_y":0,"sektor_id":2},
{"id":35,"name":"Death","x":14,"y":18,"z":0,"fraktion_id":1,"quadrant_id":3,"quadrant_x":2,"quadrant_y":0,"sektor_id":2},
{"id":36,"name":"Delta","x":16,"y":4,"z":0,"fraktion_id":1,"quadrant_id":3,"quadrant_x":2,"quadrant_y":0,"sektor_id":2},
{"id":37,"name":"Delta Prime","x":6,"y":2,"z":0,"fraktion_id":1,"quadrant_id":3,"quadrant_x":2,"quadrant_y":0,"sektor_id":2},
{"id":38,"name":"Eden","x":22,"y":18,"z":0,"fraktion_id":1,"quadrant_id":3,"quadrant_x":2,"quadrant_y":0,"sektor_id":2},
{"id":39,"name":"Famine","x":11,"y":15,"z":0,"fraktion_id":1,"quadrant_id":3,"quadrant_x":2,"quadrant_y":0,"sektor_id":2},
{"id":40,"name":"Gamma","x":11,"y":1,"z":0,"fraktion_id":1,"quadrant_id":3,"quadrant_x":2,"quadrant_y":0,"sektor_id":2},
{"id":41,"name":"J900","x":2,"y":26,"z":0,"fraktion_id":1,"quadrant_id":3,"quadrant_x":2,"quadrant_y":0,"sektor_id":2},
{"id":42,"name":"KM-252","x":27,"y":27,"z":0,"fraktion_id":1,"quadrant_id":3,"quadrant_x":2,"quadrant_y":0,"sektor_id":2},
{"id":43,"name":"New Caledonia","x":8,"y":6,"z":0,"fraktion_id":1,"quadrant_id":3,"quadrant_x":2,"quadrant_y":0,"sektor_id":2},
{"id":44,"name":"Nexus","x":26,"y":22,"z":0,"fraktion_id":1,"quadrant_id":3,"quadrant_x":2,"quadrant_y":0,"sektor_id":2},
{"id":45,"name":"Palan","x":26,"y":12,"z":0,"fraktion_id":1,"quadrant_id":3,"quadrant_x":2,"quadrant_y":0,"sektor_id":2},
{"id":46,"name":"Pestilence","x":20,"y":22,"z":0,"fraktion_id":1,"quadrant_id":3,"quadrant_x":2,"quadrant_y":0,"sektor_id":2},
{"id":47,"name":"Regallis","x":6,"y":21,"z":0,"fraktion_id":1,"quadrant_id":3,"quadrant_x":2,"quadrant_y":0,"sektor_id":2},
{"id":48,"name":"Rygannon","x":19,"y":6,"z":0,"fraktion_id":1,"quadrant_id":3,"quadrant_x":2,"quadrant_y":0,"sektor_id":2},
{"id":49,"name":"Sherwood","x":6,"y":14,"z":0,"fraktion_id":1,"quadrant_id":3,"quadrant_x":2,"quadrant_y":0,"sektor_id":2},
{"id":50,"name":"Telar","x":2,"y":16,"z":0,"fraktion_id":1,"quadrant_id":3,"quadrant_x":2,"quadrant_y":0,"sektor_id":2},
{"id":51,"name":"Valhalla","x":13,"y":22,"z":0,"fraktion_id":1,"quadrant_id":3,"quadrant_x":2,"quadrant_y":0,"sektor_id":2},
{"id":52,"name":"War","x":15,"y":27,"z":0,"fraktion_id":1,"quadrant_id":3,"quadrant_x":2,"quadrant_y":0,"sektor_id":2},
{"id":53,"name":"Xytani","x":24,"y":8,"z":0,"fraktion_id":1,"quadrant_id":3,"quadrant_x":2,"quadrant_y":0,"sektor_id":2},
{"id":54,"name":"Blockade Point Alpha","x":10,"y":6,"z":0,"fraktion_id":1,"quadrant_id":4,"quadrant_x":3,"quadrant_y":0,"sektor_id":2},
{"id":55,"name":"Blockade Point Charlie","x":20,"y":18,"z":0,"fraktion_id":1,"quadrant_id":4,"quadrant_x":3,"quadrant_y":0,"sektor_id":2},
{"id":56,"name":"Blockade Point Tango","x":23,"y":14,"z":0,"fraktion_id":1,"quadrant_id":4,"quadrant_x":3,"quadrant_y":0,"sektor_id":2},
{"id":57,"name":"CMF-A","x":10,"y":12,"z":0,"fraktion_id":1,"quadrant_id":4,"quadrant_x":3,"quadrant_y":0,"sektor_id":2},
{"id":58,"name":"Hyades","x":21,"y":7,"z":0,"fraktion_id":1,"quadrant_id":4,"quadrant_x":3,"quadrant_y":0,"sektor_id":2},
{"id":59,"name":"Lisacc","x":27,"y":25,"z":0,"fraktion_id":1,"quadrant_id":4,"quadrant_x":3,"quadrant_y":0,"sektor_id":2},
{"id":60,"name":"Mah'Rahn","x":27,"y":9,"z":0,"fraktion_id":1,"quadrant_id":4,"quadrant_x":3,"quadrant_y":0,"sektor_id":2},
{"id":61,"name":"Midgard","x":8,"y":24,"z":0,"fraktion_id":1,"quadrant_id":4,"quadrant_x":3,"quadrant_y":0,"sektor_id":2},
{"id":62,"name":"Nitir","x":15,"y":13,"z":0,"fraktion_id":1,"quadrant_id":4,"quadrant_x":3,"quadrant_y":0,"sektor_id":2},
{"id":63,"name":"Perry","x":13,"y":21,"z":0,"fraktion_id":1,"quadrant_id":4,"quadrant_x":3,"quadrant_y":0,"sektor_id":2},
{"id":64,"name":"Ragnarok","x":4,"y":11,"z":0,"fraktion_id":1,"quadrant_id":4,"quadrant_x":3,"quadrant_y":0,"sektor_id":2},
{"id":65,"name":"Rikel","x":3,"y":27,"z":0,"fraktion_id":1,"quadrant_id":4,"quadrant_x":3,"quadrant_y":0,"sektor_id":2},
{"id":66,"name":"Sumn-Kp'ta","x":27,"y":5,"z":0,"fraktion_id":1,"quadrant_id":4,"quadrant_x":3,"quadrant_y":0,"sektor_id":2},
{"id":67,"name":"Surtur","x":18,"y":25,"z":0,"fraktion_id":1,"quadrant_id":4,"quadrant_x":3,"quadrant_y":0,"sektor_id":2},
{"id":68,"name":"Tingerhoff","x":4,"y":18,"z":0,"fraktion_id":1,"quadrant_id":4,"quadrant_x":3,"quadrant_y":0,"sektor_id":2},
{"id":69,"name":"Tr'Pakh","x":23,"y":2,"z":0,"fraktion_id":1,"quadrant_id":4,"quadrant_x":3,"quadrant_y":0,"sektor_id":2},
{"id":70,"name":"Karing","x":25,"y":15,"z":0,"fraktion_id":2,"quadrant_id":5,"quadrant_x":4,"quadrant_y":0,"sektor_id":3},
{"id":71,"name":"K'n'Pakh","x":6,"y":2,"z":0,"fraktion_id":2,"quadrant_id":5,"quadrant_x":4,"quadrant_y":0,"sektor_id":3},
{"id":72,"name":"S'kha Rissth","x":17,"y":22,"z":0,"fraktion_id":2,"quadrant_id":5,"quadrant_x":4,"quadrant_y":0,"sektor_id":3},
{"id":73,"name":"S'kh'haral (1)","x":20,"y":2,"z":0,"fraktion_id":2,"quadrant_id":5,"quadrant_x":4,"quadrant_y":0,"sektor_id":3},
{"id":74,"name":"S'kh'haral (2)","x":24,"y":6,"z":0,"fraktion_id":2,"quadrant_id":5,"quadrant_x":4,"quadrant_y":0,"sektor_id":3},
{"id":75,"name":"S'kh'haral (3)","x":27,"y":21,"z":0,"fraktion_id":2,"quadrant_id":5,"quadrant_x":4,"quadrant_y":0,"sektor_id":3},
{"id":76,"name":"Sum'nH'hra","x":10,"y":6,"z":0,"fraktion_id":2,"quadrant_id":5,"quadrant_x":4,"quadrant_y":0,"sektor_id":3},
{"id":77,"name":"Sum'n L'kor","x":4,"y":22,"z":0,"fraktion_id":2,"quadrant_id":5,"quadrant_x":4,"quadrant_y":0,"sektor_id":3},
{"id":78,"name":"Sum'n Shriss","x":14,"y":11,"z":0,"fraktion_id":2,"quadrant_id":5,"quadrant_x":4,"quadrant_y":0,"sektor_id":3},
{"id":79,"name":"Sum'Tlor","x":9,"y":10,"z":0,"fraktion_id":2,"quadrant_id":5,"quadrant_x":4,"quadrant_y":0,"sektor_id":3},
{"id":80,"name":"T'K Tarak","x":7,"y":28,"z":0,"fraktion_id":2,"quadrant_id":5,"quadrant_x":4,"quadrant_y":0,"sektor_id":3},
{"id":81,"name":"T'K Urel","x":20,"y":28,"z":0,"fraktion_id":2,"quadrant_id":5,"quadrant_x":4,"quadrant_y":0,"sektor_id":3},
{"id":82,"name":"Zarnobian","x":28,"y":28,"z":0,"fraktion_id":2,"quadrant_id":5,"quadrant_x":4,"quadrant_y":0,"sektor_id":3},
{"id":83,"name":"Bordrav","x":16,"y":28,"z":0,"fraktion_id":2,"quadrant_id":6,"quadrant_x":5,"quadrant_y":0,"sektor_id":3},
{"id":84,"name":"Omega","x":12,"y":26,"z":0,"fraktion_id":2,"quadrant_id":6,"quadrant_x":5,"quadrant_y":0,"sektor_id":3},
{"id":85,"name":"Tr'l H'mass (1)","x":2,"y":9,"z":0,"fraktion_id":2,"quadrant_id":6,"quadrant_x":5,"quadrant_y":0,"sektor_id":3},
{"id":86,"name":"Tr'l H'mass (2)","x":8,"y":6,"z":0,"fraktion_id":2,"quadrant_id":6,"quadrant_x":5,"quadrant_y":0,"sektor_id":3},
{"id":87,"name":"Tr'l H'mass (3)","x":14,"y":7,"z":0,"fraktion_id":2,"quadrant_id":6,"quadrant_x":5,"quadrant_y":0,"sektor_id":3},
{"id":88,"name":"Tr'l H'mass (4)","x":20,"y":8,"z":0,"fraktion_id":2,"quadrant_id":6,"quadrant_x":5,"quadrant_y":0,"sektor_id":3},
{"id":89,"name":"Tr'l H'mass (5)","x":26,"y":4,"z":0,"fraktion_id":2,"quadrant_id":6,"quadrant_x":5,"quadrant_y":0,"sektor_id":3},
{"id":90,"name":"Tr'l H'mass (6)","x":6,"y":16,"z":0,"fraktion_id":2,"quadrant_id":6,"quadrant_x":5,"quadrant_y":0,"sektor_id":3},
{"id":91,"name":"Tr'l H'mass (7)","x":15,"y":15,"z":0,"fraktion_id":2,"quadrant_id":6,"quadrant_x":5,"quadrant_y":0,"sektor_id":3},
{"id":92,"name":"Tr'l H'mass (8)","x":21,"y":14,"z":0,"fraktion_id":2,"quadrant_id":6,"quadrant_x":5,"quadrant_y":0,"sektor_id":3},
{"id":93,"name":"Tr'l H'mass (9)","x":2,"y":22,"z":0,"fraktion_id":2,"quadrant_id":6,"quadrant_x":5,"quadrant_y":0,"sektor_id":3},
{"id":94,"name":"Tr'l H'mass (10) ","x":26,"y":21,"z":0,"fraktion_id":2,"quadrant_id":6,"quadrant_x":5,"quadrant_y":0,"sektor_id":3},
{"id":95,"name":"Tr'l H'mass (11)","x":25,"y":28,"z":0,"fraktion_id":2,"quadrant_id":6,"quadrant_x":5,"quadrant_y":0,"sektor_id":3},
{"id":96,"name":"Varni ","x":7,"y":26,"z":0,"fraktion_id":2,"quadrant_id":6,"quadrant_x":5,"quadrant_y":0,"sektor_id":3},
{"id":97,"name":"K'vt Karh (1)","x":4,"y":4,"z":0,"fraktion_id":2,"quadrant_id":7,"quadrant_x":6,"quadrant_y":0,"sektor_id":4},
{"id":98,"name":"K'vt Karh (2)","x":11,"y":9,"z":0,"fraktion_id":2,"quadrant_id":7,"quadrant_x":6,"quadrant_y":0,"sektor_id":4},
{"id":99,"name":"K'vt Karh (3)","x":16,"y":5,"z":0,"fraktion_id":2,"quadrant_id":7,"quadrant_x":6,"quadrant_y":0,"sektor_id":4},
{"id":100,"name":"K'vt Karh (4)","x":18,"y":9,"z":0,"fraktion_id":2,"quadrant_id":7,"quadrant_x":6,"quadrant_y":0,"sektor_id":4},
{"id":101,"name":"K'vt Karh (5)","x":27,"y":5,"z":0,"fraktion_id":2,"quadrant_id":7,"quadrant_x":6,"quadrant_y":0,"sektor_id":4},
{"id":102,"name":"K'vt Karh (6)","x":4,"y":16,"z":0,"fraktion_id":2,"quadrant_id":7,"quadrant_x":6,"quadrant_y":0,"sektor_id":4},
{"id":103,"name":"K'vt Karh (7)","x":13,"y":19,"z":0,"fraktion_id":2,"quadrant_id":7,"quadrant_x":6,"quadrant_y":0,"sektor_id":4},
{"id":104,"name":"K'vt Karh (8)","x":21,"y":16,"z":0,"fraktion_id":2,"quadrant_id":7,"quadrant_x":6,"quadrant_y":0,"sektor_id":4},
{"id":105,"name":"K'vt Karh (9)","x":26,"y":18,"z":0,"fraktion_id":2,"quadrant_id":7,"quadrant_x":6,"quadrant_y":0,"sektor_id":4},
{"id":106,"name":"K'vt Karh (10)","x":20,"y":24,"z":0,"fraktion_id":2,"quadrant_id":7,"quadrant_x":6,"quadrant_y":0,"sektor_id":4},
{"id":107,"name":"K'vt Karh (11)","x":28,"y":24,"z":0,"fraktion_id":2,"quadrant_id":7,"quadrant_x":6,"quadrant_y":0,"sektor_id":4},
{"id":108,"name":"K'vt Karh (12)","x":5,"y":25,"z":0,"fraktion_id":2,"quadrant_id":7,"quadrant_x":6,"quadrant_y":0,"sektor_id":4},
{"id":109,"name":"K'vt Karh (13)","x":12,"y":26,"z":0,"fraktion_id":2,"quadrant_id":7,"quadrant_x":6,"quadrant_y":0,"sektor_id":4},
{"id":110,"name":"K'vt Karh (14) ","x":23,"y":29,"z":0,"fraktion_id":2,"quadrant_id":7,"quadrant_x":6,"quadrant_y":0,"sektor_id":4},
{"id":111,"name":"S'kur (1)","x":4,"y":7,"z":0,"fraktion_id":2,"quadrant_id":8,"quadrant_x":7,"quadrant_y":0,"sektor_id":4},
{"id":112,"name":"S'kur (2)","x":23,"y":3,"z":0,"fraktion_id":2,"quadrant_id":8,"quadrant_x":7,"quadrant_y":0,"sektor_id":4},
{"id":113,"name":"S'kur (3)","x":12,"y":8,"z":0,"fraktion_id":2,"quadrant_id":8,"quadrant_x":7,"quadrant_y":0,"sektor_id":4},
{"id":114,"name":"S'kur (4)","x":25,"y":10,"z":0,"fraktion_id":2,"quadrant_id":8,"quadrant_x":7,"quadrant_y":0,"sektor_id":4},
{"id":115,"name":"S'kur (5)","x":18,"y":12,"z":0,"fraktion_id":2,"quadrant_id":8,"quadrant_x":7,"quadrant_y":0,"sektor_id":4},
{"id":116,"name":"S'kur (6)","x":3,"y":17,"z":0,"fraktion_id":2,"quadrant_id":8,"quadrant_x":7,"quadrant_y":0,"sektor_id":4},
{"id":117,"name":"S'kur (7)","x":23,"y":17,"z":0,"fraktion_id":2,"quadrant_id":8,"quadrant_x":7,"quadrant_y":0,"sektor_id":4},
{"id":118,"name":"S'kur (8)","x":9,"y":21,"z":0,"fraktion_id":2,"quadrant_id":8,"quadrant_x":7,"quadrant_y":0,"sektor_id":4},
{"id":119,"name":"S'kur (9) ","x":16,"y":26,"z":0,"fraktion_id":2,"quadrant_id":8,"quadrant_x":7,"quadrant_y":0,"sektor_id":4},
{"id":120,"name":"Pietzsch","x":23,"y":16,"z":0,"fraktion_id":1,"quadrant_id":11,"quadrant_x":0,"quadrant_y":1,"sektor_id":5},
{"id":121,"name":"Russ","x":23,"y":26,"z":0,"fraktion_id":1,"quadrant_id":11,"quadrant_x":0,"quadrant_y":1,"sektor_id":5},
{"id":122,"name":"TCSC2025","x":16,"y":10,"z":0,"fraktion_id":0,"quadrant_id":11,"quadrant_x":0,"quadrant_y":1,"sektor_id":5},
{"id":123,"name":"TCSC2195","x":16,"y":26,"z":0,"fraktion_id":0,"quadrant_id":11,"quadrant_x":0,"quadrant_y":1,"sektor_id":5},
{"id":124,"name":"Theta'C Orionis ","x":17,"y":16,"z":0,"fraktion_id":1,"quadrant_id":11,"quadrant_x":0,"quadrant_y":1,"sektor_id":5}]};